

name: m2climatlight
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - xarray
  - nc-time-axis # to deal with some time axis
  - proplot=0.6.4
  - matplotlib=3.2
  - cartopy=0.17.0
  - xesmf=0.3.0 # regrid
  - isort
  - esmpy=8.0.1
  - nbresuse # to see RAM
  - nodejs[version='>=10.0'] # for jupyterlab
  - python-graphviz # for dask visualization
  - dask # for parallelization
  - nb_conda_kernels # allow changing kernel in a notebook
  - netcdf4
  - jupyterlab_code_formatter
  - jupyterlab
  - jupyter
